main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.about, name='about'),
    # path('about/', views.about, name='about'),
    path('meals/', views.meals_index, name='index'),
    path('meals/<int:meal_id>/', views.meals_detail, name='detail'),
    path('meals/create', views.MealCreate.as_view(), name='meals_create'),
    path('meals/<int:pk>/update', views.MealUpdate.as_view(), name='meals_update'),
    path('meals/<int:pk>/delete', views.MealDelete.as_view(), name='meals_delete'),
    
    path('meals/<int:meal_id>/add_recipe/', views.add_recipe, name='add_recipe'),
    path('meals/<int:meal_id>/add_directions/', views.add_directions, name='add_directions'),
    
    path('meals/<int:meal_id>/assoc_list/<int:list_id>/', views.assoc_list, name='assoc_list'),
    path('meals/<int:meal_id>/assoc_list/<int:list_id>/delete/', views.assoc_list_delete, name='assoc_list_delete'),
    
    path('lists/', views.ListList.as_view(), name='lists_index'),
    path('lists/<int:pk>/', views.ListDetail.as_view(), name='lists_detail'),
    path('lists/create', views.ListCreate.as_view(), name='lists_create'),
    path('lists/<int:pk>/update/', views.ListUpdate.as_view(), name='lists_update'),
    path('lists/<int:pk>/delete/', views.ListDelete.as_view(), name='lists_delete'),
    
    path('meals/<int:meal_id>/add_photo/', views.add_photo, name='add_photo'),
    
    path('accounts/signup/', views.signup, name='signup'),
   
]

meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
  
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

CHOWTIME = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
        ('S', 'Snack')
)

# Create your models here.

class List(models.Model):
    quantity = models.CharField(max_length=100)
    item = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.quantity} {self.item}"
    def get_absolute_url(self):
        return reverse('lists_detail', kwargs={'pk': self.id})

class Meal(models.Model):
    day = models.CharField(max_length=100)
    date = models.CharField(max_length=100)
    name = models.CharField(max_length=150)
    lists = models.ManyToManyField(List)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('detail', kwargs={'meal_id': self.id})

class Recipe(models.Model):
    ingredients = models.CharField(max_length=100)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE) 
    def __str__(self):
        return f"Recipe Ingredients {self.ingredients}"
    
class Directions(models.Model):  
    directions = models.TextField(max_length=1000)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    def __str__(self):
        return f"Recipe Directions {self.directions}"
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for meal_id: {self.meal_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Recipe, Directions
from django import forms

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['ingredients']


class DirectionsForm(ModelForm):
    directions = forms.CharField(widget=forms.Textarea, required=False)
    class Meta:
        model = Directions
        fields = ['directions']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import RecipeForm, DirectionsForm
from .models import Meal, List, Photo

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'meal-planner-db'

# Create your views here.

# def home(request):
#     return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def meals_index(request):
    meals = Meal.objects.filter(user=request.user)
    return render(request, 'meals/index.html', {'meals': meals })

@login_required
def meals_detail(request, meal_id):
    meal = Meal.objects.get(id=meal_id)
    recipe_form = RecipeForm()
    directions_form = DirectionsForm()
    lists_meal_doesnt_have = List.objects.exclude(id__in = meal.lists.all().values_list('id'))
    return render(request, 'meals/detail.html', {'meal' : meal, 'recipe_form' : recipe_form, 'directions_form' : directions_form, 'lists' : lists_meal_doesnt_have })

@login_required
def add_recipe(request, meal_id):
    form = RecipeForm(request.POST)
    if form.is_valid():
        new_recipe = form.save(commit=False)
        new_recipe.meal_id = meal_id
        new_recipe.save()
    return redirect('detail', meal_id=meal_id)

@login_required
def add_directions(request, meal_id):
    form = DirectionsForm(request.POST)
    if form.is_valid():
        new_directions = form.save(commit=False)
        new_directions.meal_id = meal_id
        new_directions.save()
    return redirect('detail', meal_id=meal_id)

@login_required
def assoc_list(request, meal_id, list_id):
    Meal.objects.get(id=meal_id).lists.remove(list_id)
    return redirect('detail', meal_id=meal_id)

@login_required
def assoc_list_delete(request, meal_id, list_id):
    Meal.objects.get(id=meal_id).lists.remove(list_id)
    return redirect('detail', meal_id=meal_id)

@login_required
def add_photo(request, meal_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:                
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, meal_id=meal_id)
            photo.save()
        except Exception as error:
            print('Error uploading photo:', error)
            return redirect('detail', meal_id=meal_id)
        return redirect('detail', meal_id=meal_id)
        
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('about')
        else:
            error_message = "Invalid Entry = Please Try Again"
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class MealCreate(LoginRequiredMixin, CreateView):
    model = Meal
    fields = ['day', 'date', 'name']
    success_url = '/meals/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class MealUpdate(LoginRequiredMixin, UpdateView):
    model = Meal
    fields = ['day', 'date', 'name']

class MealDelete(LoginRequiredMixin, DeleteView):
    model = Meal
    success_url = '/meals/'

class ListList(LoginRequiredMixin, ListView):
    model = List
    template_name = 'lists/index.html'

class ListDetail(LoginRequiredMixin, DetailView):
    model = List
    template_name = 'lists/detail.html'

class ListCreate(LoginRequiredMixin, CreateView):
    model = List
    fields = ['quantity', 'item']

class ListUpdate(LoginRequiredMixin, UpdateView):
    model = List
    fields = ['quantity', 'item']

class ListDelete(LoginRequiredMixin, DeleteView):
    model = List
    success_url = '/lists/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About</h1>

    <p class="flow-text">
    Welcome to the Meal Planner app. Here you can plan you dishes, input your recipes, and create your shopping lists. The more you plan, the easier the app is to use. Store all your favorite recipes for quick and easy planning. Stay with us for our future updates of adding recipes directly to your meals list, breakfast/lunch/dinner catagories, and adding ingredients directly to your shopping list.</p>
    <br />
    <h4>Happy planning!</h4>

        <!-- <style>
        p {
            width: 40%;
        }
    </style> -->
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Planner</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link 
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
       
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" />
</head>
<body class="horizontal-layout">
    <style>
        body {
            background-image: url(https://i.imgur.com/Ki70XCP.jpg);
            background-size: cover;
        }
    </style>
        <header>
            <nav class="nav-wrapper">
                <style>
                .nav-wrapper {
                    background: linear-gradient(to right, purple , blue);
                }
                </style>
                <div class="container">
                    <div class="left brang-logo">Meal Planner</div>
                    <a href="" class="sidenav-trigger" data-target="mobile-menu">
                        <i class="material-icons">menu</i>
                    </a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="{% url 'about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'index' %}">View All Meals</a></li>
                        <li><a href="{% url 'meals_create' %}">Add a Meal</a> </li>
                        <li><a href="{% url 'lists_index' %}">View Shopping List</a></li>
                        <li><a href="{% url 'lists_create' %}">Add Shopping List Item</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                    <ul class="sidenav grey lighten-2" id="mobile-menu">
                        <li><a href="{% url 'about' %}">About</a></li>

                        <li><a href="{% url 'index' %}">View All Meals</a></li>
                        <li><a href="{% url 'meals_create' %}">Add a Meal</a> </li>
                        <li><a href="{% url 'lists_index' %}">View Shopping List</a></li>
                        <li><a href="{% url 'lists_create' %}">Add Shopping List Item</a></li>
                    </ul>
                    
                </div>
            </nav>
        </header>
        <main class="container"> {% block content %} {% endblock %}</main>
        <footer class="page-footer blue">
            <style>
                .page-footer {
                    background: linear-gradient(to right, purple , blue);
                }
            </style>
            <div class="right">
                All Rights Reserved &copy; 2022 Meal Planner &nbsp;
            </div>
        </footer>
       <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script>
            $(document).ready(function(){
                $('.sidenav').sidenav();
            })
        </script>
    </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Welcome</h1>



{% endblock %}

main_app/templates/lists/detail.html
{% extends 'base.html' %} {% block content %}
<div class="card-panel">

    <h1>Success:</h1>
    <h3>Item Added to Grocery List</h3>
</div>
<a href="{% url 'lists_index' %}">Grocery List</a>

    <!-- =================================LIST ADD==================================== -->
    <!-- <div class="row">
        <div class="col s6">
            <h3>{{meal.name}}</h3>
            {% if meal.lists.count %} {% for list in meal.lists.all %}
            <div class="card">
                <div class="card-content">
                    <div class="card-title">
                        <span>{{ meal.name }}</span>
                    </div>
                </div>
            <div class="card-action">
                <form
                    action="{% url 'assoc_list_delete' meal.id list.id %}"
                    method="POST">
                {% csrf_token %}
                        <button type="submit" class="btn red">Delete</button>
                </form>
            </div>
        </div>
            {% endfor %} {% else %} 
            <h5>No Lists</h5>
            {% endif %}
        </div>
        <div class="col s6">
        <h3> Grocery Lists </h3>
        {% if lists.count %} {% for list in lists.all %}
        <div class="card">
            <div class="card-content">
                <div class="card-title">
                    <span>{{ list.quantity}}</span>
                    {{ list.item }}
                </div>
            </div>
            
            <div class="card-action">
                <form action="{% url 'assoc_list' meal.id list.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h5>{{meal.name}} already has a list</h5>
        {% endif %}
     </div>
    </div> -->

{% endblock %}

main_app/templates/lists/index.html
{% extends 'base.html' %} {% block content %}

<h1>Shopping List</h1>

{% for list in object_list %}
<div>
   <form action="#">
    {% csrf_token %}
    <p>
        <label>
            <input type="checkbox" />
            <span>{{list.quantity}} {{list.item}} </span>
        </label>
    </p>
    </form>
{% endfor %}
</div>
<div>

{% for recipe in object_recipe %}
   <form action="#">
    {% csrf_token %}
    <p>
        <label>
            <input type="checkbox" />
            <span>{{recipe.ingredients}} </span>
        </label>
    </p>
    </form>
    {% endfor %}

</div>


{% endblock %}

main_app/templates/main_app/list_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Grocery List</h1>

<h4>
    Are you sure you want to erase this Grocery List
    <span class="teal-text">{{ objects.name }}</span>?
</h4>

<form action="" method="POST">
    {%  csrf_token %}
    <input type="submit" value="Yes Delete!" class="btn" />
    <a class="btn blue"  href="{% url 'index' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/list_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}
<h1>Update {{ object.name }}</h1>
{% else %}
<h1>Add Grocery List Item</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update List Item {% else %} Add List Item {% endif %}" />
</form>

{% endblock %}

main_app/templates/main_app/meal_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete</h1>

<h4>
    Are you sure you want to erase this Meal
    <span class="teal-text">{{ objects.name }}</span>
</h4>

<form action="" method="POST">
    {%  csrf_token %}
    <input type="submit" value="Yes Delete!" class="btn" />
    <a href="{% url 'detail' meal.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/meal_form.html
{% extends 'base.html' %} {% block content %}

{% if object %}
<h1>Edit<span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add Meal</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn" />
</form>

{% endblock %}

main_app/templates/meals/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class="center">{{meal.name}}</h1>
<div class="row">
    <div class="col s12">
        {% for photo in meal.photo_set.all %}
            <img class="responsive-img card" src="{{photo.url}}" alt="{{meal.name}}">
        {% empty %}
            <div class="center card-panel text-teal center-align">No Photos UpLoaded</div>
        {% endfor %}
        <div class="card-action">
            <a href="{% url 'meals_update' meal.id %}">Edit</a>
            <a href="{% url 'meals_delete' meal.id %}">Delete</a>
        </div>
    </div>
</div>

<div class="col s6">
    <div class="card">
        <div class="card-content">
            <h5>Ingredients:</h5>
            {% for recipe in meal.recipe_set.all %}
            <p>{{recipe.ingredients}}</p>
            {% endfor %}
        </div>
    </div>
</div>

<div class="col s6">
    <div class="card">
        <div class="card-content">
            <h5>Directions:</h5>
            {% for directions in meal.directions_set.all %}
            <p>{{directions.directions}}</p>
            {% endfor %}
        </div>
    </div>
</div>
  
<br /> 

<div class="card-panel">
    <form action="{% url 'add_recipe' meal.id %}" method="POST">
        {% csrf_token %} {{ recipe_form.as_p }}
        <input type="submit" class="btn" value="Add Ingredients" />
    </form>
</div>

<div class="card-panel">
    <form action="{% url 'add_directions' meal.id %}" method="POST">
        {% csrf_token %} {{ directions_form.as_p }}
        <input type="submit" class="btn" value="Add Directions" />
    </form>
</div>

<form
    action="{% url 'add_photo' meal.id %}"
    enctype="multipart/form-data"
    method="POST"
    class="card-panel"> 
    {% csrf_token %}
    <input type="file" name="photo-file" />
    <br /> <br />
    <input type="submit" class="btn" value="Upload Photo" />
</form>


    <!-- =================================LIST ADD==================================== -->
    <!-- <div class="row">
        <div class="col s6">
            <h3>{{meal.name}}</h3>
            {% if meal.lists.count %} {% for list in meal.lists.all %}
            <div class="card">
                <div class="card-content">
                    <div class="card-title">
                        <span>{{ meal.name }}</span>
                    </div>
                </div>
            <div class="card-action">
                <form
                    action="{% url 'assoc_list_delete' meal.id list.id %}"
                    method="POST">
                {% csrf_token %}
                        <button type="submit" class="btn red">Delete</button>
                </form>
            </div>
        </div>
            {% endfor %} {% else %} 
            <h5>No Lists</h5>
            {% endif %}
        </div>
        <div class="col s6">
        <h3> Grocery Lists </h3>
        {% if lists.count %} {% for list in lists.all %}
        <div class="card">
            <div class="card-content">
                <div class="card-title">
                    <span>{{ list.quantity}}</span>
                    {{ list.item }}
                </div>
            </div>
            
            <div class="card-action">
                <form action="{% url 'assoc_list' meal.id list.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h5>{{meal.name}} already has a list</h5>
        {% endif %}
     </div>
    </div> -->
{% endblock %}

main_app/templates/meals/index.html
{% extends 'base.html' %} {% block content %}

<h1>Your meals</h1>

<div style="display: flex; flex-flow: row wrap;">
{% for meal in meals %}
<!-- <div class="row"> -->
    <div class="col s3" style="margin: 2px;">
            <div class="card-panel hoverable z-depth-1" style="width: 130px; height: 150px;">
                <style>
                    .card-panel {
                        background: whitesmoke;
                        opacity: .6;
                    }
                </style>
                <a href="{% url 'detail' meal.id %}">
                    <div class="card-content">
                        <span class="card-title blue-text text-darken-4">{{ meal.day }}</span>
                        <p class="purple-text text-darken-4"> {{meal.date}} </p>
                        <p>{{meal.name}}</p>  
                    </div>
                </a>
            </div>
        </div>
        <!-- </div> -->
        {% endfor %} 
    </div>
        
{% endblock %}